name: "가격 급변 알림"
trigger:
  type: price_change
reaction:
  agent: "market_analyst"
  approval: auto
  channel: push
  promptContext: >-
    {data.symbol} 가격이 {data.changePercent}% 변동했습니다.
    현재가: ${data.price} / 이전가: ${data.previousPrice}
    이 가격 변동의 원인과 단기 전망을 2-3문장으로 한국어로 분석해주세요.
